-- Target schema: customer_portal. The table shape intentionally matches CRM
-- so the same hardened dispatcher can be used with a separate Portal client.
CREATE TABLE portal_application_request_audit_outbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  application_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  environment_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  actor_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  actor_id VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  actor_name VARCHAR(200) NOT NULL DEFAULT '',
  action VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  resource_type VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  resource_id VARCHAR(128) NOT NULL DEFAULT '',
  request_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  method VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  route VARCHAR(500) NOT NULL,
  http_status INT NOT NULL DEFAULT 0,
  result VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  reason_code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  risk_level VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  delivery_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  next_attempt_at DATETIME(3) NULL,
  locked_by VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  locked_until DATETIME(3) NULL,
  last_error_code VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  occurred_at DATETIME(3) NOT NULL,
  completed_at DATETIME(3) NULL,
  delivered_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_request_audit_event (event_id),
  KEY idx_request_audit_tenant_request (tenant_id, request_id),
  KEY idx_request_audit_delivery (delivery_status, next_attempt_at, id),
  CONSTRAINT chk_portal_request_audit_delivery CHECK (delivery_status IN ('STARTED','PENDING','PROCESSING','RETRY','DELIVERED')),
  CONSTRAINT chk_portal_request_audit_result CHECK (result IN ('SUCCESS','FAILURE','DENIED')),
  CONSTRAINT chk_portal_request_audit_actor CHECK (actor_type IN ('SYSTEM','USER','MACHINE')),
  CONSTRAINT chk_portal_request_audit_risk CHECK (risk_level IN ('LOW','MEDIUM','HIGH','CRITICAL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
